# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Install tree-sitter dependency
  ansible.builtin.include_role:
    name: jcook3701.source.tree_sitter
    file: tree-sitter-install.yml

- name: Import emacs vars
  ansible.builtin.include_vars:
    file: emacs.yml

- name: Source Package Build Initialization Routine
  ansible.builtin.include_role:
    name: jcook3701.utils.autobuild
    task_from: pkg-source-build-init-routine.yml
  vars:
    autobuild_git_repo: "{{ emacs_git_repo }}"
    autobuild_build: "{{ emacs_build }}"
    autobuild_pkgs: "{{ emacs_pkgs }}"
  when: sudo_user is defined
