# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
git_repo:
  provider: "github"
  owner: "keithbowes"
  name: "meson-install"
#  tags: [] # defaults to latest tag or master workspace

build:
  enabled: false
  script: "None"
  bashrc:
    enabled: true
    block: |
      export PATH="$HOME/{{ build_paths.home }}/{{ git_repo.name }}/:$PATH"
  checkinstall: false
