# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Install qtbase dependency
  ansible.builtin.include_role:
    name: jcook3701.source.qtbase
    tasks_from: qtbase-install.yml

- name: Install libportal dependency
  ansible.builtin.include_role:
    name: jcook3701.source.libportal
    tasks_from: libportal-install.yml

- name: Install libei dependency
  ansible.builtin.include_role:
    name: jcook3701.source.libei
    tasks_from: libei-install.yml

- name: Import deskflow vars
  ansible.builtin.include_vars:
    file: "deskflow.yml"

- name: Source Package Build Initialization Routine
  ansible.builtin.include_role:
    name: jcook3701.utils.autobuild
    tasks_from: pkg-source-build-init-routine.yml
  vars:
    autobuild_git_repo: "{{ deskflow_git_repo }}"
    autobuild_build: "{{ deskflow_build }}"
    autobuild_pkgs: "{{ deskflow_pkgs }}"
  when: sudo_user is defined
