# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Collect running user facts
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: sudo_user_facts.yml
  when: sudo_user is not defined

- name: Import meson-install vars
  ansible.builtin.include_vars:
    file: "pkgs-software-development/pkgs-source/meson-install/meson-install.yml"

- name: Source Package Build Initialization Routine
  ansible.builtin.include_role:
    name: jcook3701.utils.general
    task_from: pkg-source-build-init-routine.yml
  when: sudo_user is defined

# TODO: Move to /usr/local/bin
