# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install deskflow from source code to localhost
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install deskflow
      ansible.builtin.include_role:
        name: jcook3701.source.deskflow
        tasks_from: deskflow-install.yml
