# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Configure Emacs Init.el on localhost
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Configure Emacs Init.el
      ansible.builtin.include_role:
        name: jcook3701.source.emacs
        tasks_from: emacs-configure.yml
