# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Install libportal from source code to localhost
  hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Install libportal
      ansible.builtin.include_role:
        name: jcook3701.source.libportal
        tasks_from: libportal-install.yml
