# SPDX-FileCopyrightText: Copyright © 2026, Jared Cook
# SPDX-License-Identifier: AGPL-3.0-or-later
---
git_repo:
  provider: "github"
  owner: "flatpak"
  name: "libportal"
  tags: [] # defaults to latest tag or master workspace

build:
  enabled: true
  script: "meson-ninja"
  checkinstall: true

pkgs:
  apt: [meson, ninja-build, pkg-config, gcc, libglib2.0-dev, wget]
  dnf: []
  pacman: []
